### ISSUE TITLE
Major refactoring of calibration chain

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/ctapipe#1026]
Transfer of #1023 into an issue, to organise the different pull requests involved in the major refactoring.

## 1. PR #1023
- [x] Remove dependance of tests on files from ctapipe_extra (PR #1023)
- [x] Add values to unit tests to ensure behaviour is kept for upcoming refactoring (PR #1023)
- [x] Refactor `ChargeExtractors` into a composition approach for simplification (replacing the inheritance approach) (see #907) (PR #1023)

## 2. PR #1032 
- [x] Replace C function used in the neighbor charge extractor with a Numba implementation

## 3. PR #1033 
- [x] Create `ImageExtractor` class to replace `ChargeExtractor` and `WaveformCleaner`
- [x] Make `ImageExtractor` return two parameters per event - charge and peak time (floating point)
- [x] A simple peak time extraction is using the weighted average (see #1021)
- [x] Switch to using `__call__` (see #1022 and #1024)

## 4. PR #1038
- [x] Optimisation study, and consideration of using numba for charge extraction

## 5. PR #1045 
- [x] Consider more robust calculations of pulse_time (see #1033)
- [x] Optimisation and improvement of pulse time extraction

## 6. PR #1046 
- [x] Retire CameraR1Calibrator, make filling r1 waveform container the responsibility of the `EventSource`

## 7. PR #1048
- [x] Simplify calibration chain into a single class, which is composed of individual calibration steps (gain selection, data reduction, image extraction, charge calibration)

## 8. PR #1095 
- [x] Gain selecting (replacing #683)

## 9. PR #1146 
- [x] Combine `extract_pulse_time_around_peak` and `sum_samples_around_peakpos`

## 10. PR #1155
- [x] Improve passing of neighbors to algorithm (see #909)
- [x] Enable individual calibration config per telescope (#703 #702)

## 11. PR #1160
- [x] Add flat field, absolute signal, and pedestal calibration to DL1Calibrator

## 12. PR #1242 
- [x] Move integration_correction from CameraCalibrator to ImageExtractors
- [x] Apply sampling_rate in ImageExtractors

## 13. PR #1283 
- [x] Update documentation and notebooks to describe new calibration chain

# Delegated to other issues:
- [x] Restructure calib modules and location of ImageExtractors
   - #1205 and #1037
- [x] Classes to fill calibration fields in event
   - #1226 and #1147 and #1037 
- [x] Extract pulse width from waveform
   - #1243

**Comment by kosack** [comment]
Can we add gain channel selection to this list as well, since we're at it? I never finished merging in the code to do it, so it's better now to start fresh.  We can remove the old GainSelector hierarchy and just replace it with simple functions for now.  The WaveformReducer should then return charge as a 1D array, not per channel.
