### ISSUE TITLE
DL1 Data Processing Tool

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1066]
This is a "parent" issue to track some developments needed to implement proper DL1 data handling in ctapipe.  This is part of a larger issue to make a standard chain (See #977)

## Assumptions:
- DL1 data are in HDF5 format
- development should be synchronized to the *protopipe* development (the final Tool should replace the *protopipe* dl1 script, *dl1-data-handler*, and optionally later also the *lstchain* dl1 script,  if that is useful)

## Tasks:

- [x] refactor basic image calibration code (see #1026 )
- [x] Do gain-selection during  or after calibration and charge extraction (so that we have only a single DL1 image), (See #1026, *additional tasks*)
- [x] Decide on DL1 file format/layout: (discussion: #1059 )
- [x] Implement writing SubarrayDescription to an HDF5 file 
- [x] Implement creating a SubarrayDescription from an HDF5 file (written with prev step)
- [x] Implement standard ctapipe DL0 -> DL1  Tool (based on protopipe, lstchain, dl1-dumper, etc)
    - Metadata tables:
        - [x] simulation run configuration
        - [x] observation configuration 
    - Event tables:
        - [x] monte-carlo events table
        - [x] trigger table
        - [x] standard calibrated image tables  (easy, just needs calib)
        - [x] standard image parameter tables  (requires image processing chain and configuration thereof)
    - Monitoring tables (lower priority for now, but needed later)
        - [x] pointing correction table 
        - [x] calibration monitoring (see implementation in LSTCamEventSource for example)
- [ ] Implement a DL1EventSource that reads output from the DL1 tool described in prev step  so that a DL2 tool can also be created. 
- [x] Ensure the DL1 tool can be configured by a user (via config file and command-line) and that the input and output configuration is tracked and stored in the provenance  metadata (see #1052)
- [x] store full provenance  metadata in output file

**Comment by kosack** [comment]
Just to note, I've made big progress on this and have a prototype working.  During its development, i found a number of small bugs or missing features in ctapipe, so I will first start (in the next week or so) to create pull requests for those changes before committing the full tool.

**Comment by kosack** [comment]
I will close this, since it's all implemented (except for a DL1EventSource, but that can be a separate issue)
