### ISSUE TITLE
Camera and pointing calibration API

### ISSUE THREAD

**Issue by TjarkMiener** [cta-observatory/ctapipe#2542]
This issue summarizes the suggestion for camera and pointing calibration API discussed in the [ctapipe-dev call (5.4.2024)](https://indico.cta-observatory.org/event/5513/contributions/44982/attachments/25599/37472/20240404_CamCalibAPI_TjarkMiener.pdf) and aims to divide the implementation of the camera and pointing calibration API into sub-tasks, which will be addressed in dedicated PRs.

- [x] Processing (non-gainselected) calibration data using the `process-tool`. #2529 by @Hckjs 
- [x] Add an image extractor for the variance of the waveforms. #2543 @ctoennis 
- [x] Add API for the statistical calculation of pixel-wise values over a given time interval (mean, median, variance, std …), i.e. `StatisticsAggregator`. Different aggregators can be based on numpy/scipy; [astropy sigma clipping](https://docs.astropy.org/en/stable/api/astropy.stats.sigma_clipped_stats.html) #2554 @TjarkMiener 
- [x] Add OutlierDetector components #2604 @TjarkMiener 
- [x] Adjust `StatisticsAggregator` for star tracking purposes @ctoennis 
- [x] Add API for the `CalibrationCalculator`, which holds different subcomponents for the calculation of camera coefficients, e.g. FFactor method. #2609 @TjarkMiener
- [x] Add a pointing correction component using star tracking @ctoennis 
- [x] Implementation of orchestrating tools and workflows (telescope specific tools and routines  in `calibpipe` directly; generic tools in `ctapipe`) #2628 @TjarkMiener @ctoennis 

Related issues:  #1041 #1147 #1836 #1037 #2439

Please comment in case something is missing or we should follow a different path forward @Hckjs @FrancaCassol @mexanick. Discussion on specific sub-tasks can be moved to a dedicated issue.

**Comment by mexanick** [comment]
All planned tasks have been implemented.
